### ISSUE TITLE
Thank you for this project + few questions

### ISSUE THREAD

**Issue by Macleykun** [penguintutor/pixel-server#1]
I've found your project after looking for a web version to control my rgbw ring (i couldn't get led-control to work sadly).

Your project did work! And i'm really happy with it! Thank you for opensourcing this :-).

I wanted to ask a few things.
- Is it possible to also change the brightness trough the dashboard? (for RGB but also the white value itself)
- Having the Rainbow cycle be more granualar? So that the change of color is almost unnoticable
- Own hex color picker/input? Like let's say i want to add a specific pink/red
- I know using cron it's possible to control what when to do. But maybe it's possible to also integrate this trough the dashboard itself?
- On an iphone/smaller device i noticed that the text on the colors are very small (the other text is ok/doable). I did notice it's plain html so i can look at this myself and also make a pull for something that scales a bit better. I would also add some padding from the left and right (so that the speed element isn't using the full width of the body).

Once i have the time (i hope sunday). I can contribute a docker container perhaps that makes using this even easier (tho users have to check the config file before launching). Technically this could be done with environement variables, but this might be a bit to much.

I can also submit some documentation about pm2, which is more for JS/node apps but it's like systemd but better imo.
![image](https://user-images.githubusercontent.com/26381427/160133792-e1ee076d-926c-4d6d-bd9d-6a314d771288.png)

The command would be:
pm2 start python --name="Pixel-Server" --update-env -- /home/${USER}/pixel-server/pixelserver.py

While i haven't started with home assistant, you think it's also possible to integrate home assistant with this project?

I'm curious what you think of the above :-) Again thank you for this project! I'm really happy that this one worked with my pi + neopixel!

**Comment by penguintutor** [comment]
> Is it possible to also change the brightness trough the dashboard? (for RGB but also the white value itself)

Not at the moment. That is something I may add in future. There are two ways this could be achieved, one by setting the value for the entire pixel strip, the other by reducing the color codes in the HTML. The first would likely work better with the RGBW although I haven't looked into that yet. 

> Having the Rainbow cycle be more granualar? So that the change of color is almost unnoticable

That's not something I've looked into, it would mean having to update the LEDs much more quickly so may have a performance issue.

> Own hex color picker/input? Like let's say i want to add a specific pink/red

At the moment that is coded in the HTML. I may look at putting that into a separate config file, but I don't think that there would be much benefit to adding it through the web interface as the colors are not that noticeably different when displayed on the LEDs.

> I know using cron it's possible to control what when to do. But maybe it's possible to also integrate this trough the dashboard itself?

It's something I've thought about, but would need a significant change to how it works and it's not really a priority.

>On an iphone/smaller device i noticed that the text on the colors are very small (the other text is ok/doable). I did notice it's plain html so i can look at this myself and also make a pull for something that scales a bit better. I would also add some padding from the left and right (so that the speed element isn't using the full width of the body).

The font size is all contained within the CSS file. The colour text is intentionally slightly smaller than the other text as it's less important, typically the color would be selected by clicking on the appropriate color rather than reading the text. I mainly added the text as an accessibility feature. 

I've not created any packages for the code at the moment as it's only early days. There are some other features I would like to add in future before creating a full release. In the meantime using github clone makes it easy for users to upgrade to a new version when it becomes available. 

I don't really see any advantages to using pm2 and that would just add an additional dependency as it's not included as standard on the Raspberry Pi.

**Comment by Macleykun** [comment]
heya, sure thing :) agreed on those!
